# This is a basic workflow to help you get started with Actions

name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4    # 
      - name: Run a one-line script
        run: echo Hello, world!

  static-code-analysis:
    runs-on: ubuntu-latest
    needs: [Compile]
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

  security-check-sast:
    runs-on: ubuntu-latest
    needs: [Compile]    
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: echo Hello, Shripad!

  security-check-sca:
    runs-on: ubuntu-latest
    needs: [Compile]
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: echo Hello, Shripad!

  unit-testing:
    runs-on: ubuntu-latest
    needs: [security-check-sca]
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: echo Hello, Shripad!        

  Integration-testing:
    runs-on: ubuntu-latest
    needs: [security-check-sca]
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: echo Hello, Shripad!        

  security-check:
    runs-on: ubuntu-latest
    needs: [Integration-testing]
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: echo Hello, Shripad!        

  build-docker-image:
    runs-on: ubuntu-latest
    needs: [unit-testing, Integration-testing]
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: echo Hello, Shripad!        

  uploading-image:
    runs-on: ubuntu-latest
    needs: [build-docker-image]
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: echo Hello, Shripad!        

  dev-deployment:
    runs-on: ubuntu-latest
    needs: [uploading-image]
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: echo Hello, Shripad!

  qa-deployment:
    runs-on: ubuntu-latest
    environment: QA
    needs: [dev-deployment]
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: echo Hello, Shripad!                

  functional-testing:
    runs-on: ubuntu-latest
    needs: [qa-deployment]
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: echo Hello, Shripad!

  End-to-End-testing:
    runs-on: ubuntu-latest
    needs: [functional-testing]
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: echo Hello, Shripad!

  prod-deployment:
    runs-on: ubuntu-latest
    needs: [functional-testing, End-to-End-testing]
    environment: PROD
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: echo Hello, Shripad!        